
open XNum;
open Runtime;
open VM;
open Types;
open ParseState;

value wrap_ps   : (parse_state -> unit) -> partial_value;
value unwrap_ps : string -> ref (parse_state -> unit) -> unknown -> unit;
value decode_ps : string -> unknown -> (parse_state -> unit);

value execute_ps_command_unkown : string -> unknown -> parse_state -> unit;
value execute_ps_command        : string -> UCStream.istream -> (parse_state -> unit);
value encode_command            : string -> command -> partial_value;
value decode_command            : string -> unknown -> unknown -> command;

value ps_get_global             : unknown -> list unknown -> unit;
value ps_set_global             : unknown -> list unknown -> unit;
value ps_next_char              : unknown -> unknown -> unknown -> unit;
value ps_get_char               : unknown -> list unknown -> unit;
value ps_remove_chars           : unknown -> unknown -> unknown -> unit;
value ps_insert_string          : unknown -> unknown -> unknown -> unit;
value ps_location               : unknown -> unknown -> unknown -> unit;
value ps_arg_expanded           : unknown -> unknown -> unknown -> unit;
value ps_arg_execute            : unknown -> list unknown -> unit;
value ps_arg_num                : unknown -> unknown -> unknown -> unit;
value ps_arg_int                : unknown -> unknown -> unknown -> unit;
value ps_arg_skip               : unknown -> unknown -> unknown -> unit;
value ps_arg_dim                : unknown -> unknown -> unknown -> unit;
value ps_arg_key_val            : unknown -> unknown -> unknown -> unit;
value ps_arg_dict               : unknown -> list unknown -> unit;
value ps_opt_expanded           : unknown -> list unknown -> unit;
value ps_opt_key_val            : unknown -> unknown -> unknown -> unit;
value ps_opt_int                : unknown -> list unknown -> unit;
value ps_arg_TeX_dim            : unknown -> unknown -> unknown -> unit;
value ps_current_mode           : unknown -> unknown -> unknown -> unit;
value ps_open_node_list         : unknown -> unknown -> unknown -> unit;
value ps_close_node_list        : unknown -> list unknown -> unit;
value ps_add_node               : unknown -> unknown -> unknown -> unit;
value ps_set_default_char_cmd   : unknown -> list unknown -> unit;
value ps_define_command         : unknown -> list unknown -> unit;
value ps_define_pattern         : unknown -> list unknown -> unit;
value ps_save_command           : unknown -> unknown -> unknown -> unit;
value ps_restore_command        : unknown -> unknown -> unknown -> unit;
value ps_save_pattern           : unknown -> unknown -> unknown -> unit;
value ps_restore_pattern        : unknown -> unknown -> unknown -> unit;
value ps_lookup_command         : unknown -> list unknown -> unit;
value ps_push_env               : unknown -> list unknown -> unit;
value ps_pop_env                : unknown -> list unknown -> unit;
value ps_set_env_args           : unknown -> unknown -> unknown -> unit;
value ps_top_env                : unknown -> list unknown -> unit;
value ps_lookup_env             : unknown -> list unknown -> unit;
value ps_define_env             : unknown -> list unknown -> unit;
value ps_shipout_pages          : unknown -> list unknown -> unit;
value ps_new_page_layout        : unknown -> list unknown -> unit;
value ps_new_galley             : unknown -> list unknown -> unit;
value ps_new_area               : unknown -> list unknown -> unit;
value ps_declare_font           : unknown -> list unknown -> unit;
value ps_define_math_symbol     : unknown -> list unknown -> unit;
value ps_define_root_symbol     : unknown -> list unknown -> unit;
value ps_define_math_accent     : unknown -> list unknown -> unit;
value ps_set_colour             : unknown -> unknown -> unknown -> unit;
value ps_set_bg_colour          : unknown -> unknown -> unknown -> unit;
value ps_set_alpha              : unknown -> unknown -> unknown -> unit;
value ps_draw                   : string -> Graphic.path_cmd -> unknown -> unknown -> unknown -> unit;
value ps_set_line_width         : unknown -> unknown -> unknown -> unit;
value ps_set_line_cap           : unknown -> unknown -> unknown -> unit;
value ps_set_line_join          : unknown -> unknown -> unknown -> unit;
value ps_set_miter_limit        : unknown -> unknown -> unknown -> unit;
value ps_set_math_code          : unknown -> list unknown -> unit;
value ps_new_counter            : unknown -> list unknown -> unit;
value ps_get_counter            : unknown -> list unknown -> unit;
value ps_set_counter            : unknown -> list unknown -> unit;
value ps_add_reference          : unknown -> list unknown -> unit;
value ps_reference_exists       : unknown -> list unknown -> unit;
value ps_lookup_reference       : unknown -> list unknown -> unit;
value ps_fold_references        : unknown -> list unknown -> unit;
value ps_store_old_references   : unknown -> unknown -> unit;
value ps_compare_references     : unknown -> unknown -> unknown -> unit;
value ps_write_references       : unknown -> unknown -> unknown -> unit;
value ps_dvi_special            : unknown -> unknown -> unknown -> unit;
value ps_warning                : unknown -> unknown -> unknown -> unit;
value ps_error                  : unknown -> unknown -> unknown -> unit;
value ps_execute_next_char      : unknown -> unknown -> unknown -> unit;
value ps_execute_stream         : unknown -> unknown -> unknown -> unit;
value ps_execute_argument       : unknown -> unknown -> unit;
value ps_run_parser             : unknown -> list unknown -> unit;

